version: "3.8"

services:
  localstack:
    container_name: "localstack-main"
    image: localstack/localstack:latest
    # environment:
    #   - SERVICES=s3,sqs,ses,secretsmanager,cloudwatch
    #   - DEFAULT_REGION=sa-east-1
    #   - AWS_DEFAULT_REGION=sa-east-1
    #   - DEBUG=1
    #   - DATA_DIR=/tmp/localstack/data
    #   - SKIP_SSL_CERT_DOWNLOAD=1
    #   - AWS_ACCESS_KEY_ID=admin
    #   - AWS_SECRET_ACCESS_KEY=admin
    #   - AWS_REGION=sa-east-1
    #   - SQS_ENDPOINT_STRATEGY=off
    #   - LOCALSTACK_HOST=${AWS_URL:-localhost}    
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (Pro)
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.volume:/var/lib/localstack"
    networks:
      ls:
        # Set the container IP address in the 10.0.2.0/24 subnet
        ipv4_address: 10.0.2.20
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    init: true
    env_file:
      - .env
    dns:
      # Set the DNS server to be the LocalStack container
      - 10.0.2.20
    networks:
      - ls

networks:
  ls:
    ipam:
      config:
        # Specify the subnet range for IP address allocation
        - subnet: 10.0.2.0/24